### ISSUE TITLE
Recheck for concurrency level after initial block

### ISSUE THREAD

**Issue by shmcfarl** [openclarity/functionclarity#105]
Once a block is performed, the function event concurrency is set to 0. If the function owner/admin has the rights, they can set the concurrency back to a non-zero value. FunctionClarity does not check the concurrency value again after the initial block. A continuous check should be performed on the concurrency value.

**Comment by shmcfarl** [comment]
Has this issue been reviewed @openclarity/functionclarity-maintainers?

**Comment by embonshai** [comment]
Sorry, I forgot to update but I already implemented it

**Comment by embonshai** [comment]
https://github.com/openclarity/functionclarity/pull/124

**Comment by shmcfarl** [comment]
@embonshai can you provide a new binary that includes the changes referred to in #124?

**Comment by embonshai** [comment]
done
