### ISSUE TITLE
Expand CONTRIBUTING.md guidance

### ISSUE THREAD

**Issue by justaugustus** [openclarity/functionclarity#72]
Example: https://github.com/kubernetes/sig-release/blob/master/CONTRIBUTING.md
(I can vouch for this one, as I wrote it :))

**Comment by embonshai** [comment]
Hi
I created an initial contribution guide which is derived from yours as you suggested, please let me know what you think.
https://github.com/openclarity/functionclarity/pull/160

**Comment by lelia** [comment]
This project has been publicly archived. Please visit **[github.com/openclarity](https://github.com/openclarity)** or **[openclarity.io](https://openclarity.io)** to discover our other projects!
